### ISSUE TITLE
How to get all medias when there are multiple medias in a post?

### ISSUE THREAD

**Issue by seriaati** [Lexedia/VixBluesky#21]
In the README it is mentioned that adding `r.` in front of `bskyx.app` can get the direct media link. But when a post, like https://bskyx.app/profile/seria.moe/post/3l7otcas2my2z have multiple medias, this will only get the first one. How to get all of them?

**Comment by Lexedia** [comment]
Hi, this is unfortunately not possible to display multiple images directly because of discord. The only way to have a gallery view would either be to generate dynamically an image from the base images, or using the base endpoint (removing `r.`).
An other way would be to have an url for each image, eg `/postid`  would be the first image, `/postid/2` would return the second and so on.

**Comment by seriaati** [comment]
Haha, I know it's not possible to show a gallery layout with just **one** link. My experience with fxtwitter is that they have an API that gets the details of a post, e.g. https://api.fxtwitter.com/hitsuki_sub/status/1851232524774539693, maybe you can reference to that. Fxtwitter also supports the other method you mentioned, using `postid/index`, so maybe you can implement both (one for developers, one for end users).

**Comment by Lexedia** [comment]
You can append `/json` at the end of your url to get the data returned by bluesky if that's what you want.

**Comment by seriaati** [comment]
Yes, this is what I'm looking for, thank you!
