### ISSUE TITLE
The embed fails when I changed my handle to not use the default '.bsky.social' domain

### ISSUE THREAD

**Issue by AmewaTakahashi** [Lexedia/VixBluesky#24]
![image_2024-11-17_221838548](https://github.com/user-attachments/assets/4984a536-b6a5-45bf-8162-de2813e54900)

**Comment by Lexedia** [comment]
That's odd., i can perfectly curl bskyx and it sucessfully responds with a 200 status
![image](https://github.com/user-attachments/assets/a73e2718-c360-42d0-aa9b-109ae70b6f5e)
I see some errors that needs to be fixed, but this isn't related tho.

This is from, it seems, discord's side.
![image](https://github.com/user-attachments/assets/f0640aab-bd0b-4953-9ff4-589e3743ebe8)

Unfortunately, without more context i can't really do something, it may be related to #18 
Ill keep this issue open, if anyone wants to provide other sources that may cause this, it'd be very kind <3

EDIT: To be clear, switching from a *.bsky.social to a custom handle doesn't affect much how it works

EDIT2: Also, my dumbass forgot to ask you but, are you using a custom PDS instance or the default one provided by bluesky? Custom PDS aren't supported at this time, so maybe this is where the issue is...

**Comment by AmewaTakahashi** [comment]
I'm not sure what does PDS stands for, also the .vtubers.social domain was provided for free via this site
https://vtubers.social

**Comment by Lexedia** [comment]
A PDS is a Personal Data Server, if you use a custom PDS, whenever you upload an attachment to bluesky, it'll be sent to the said PDS (it's asked when you first create an account on bsky). But judging by your reaction, I'd assume you're using the base one.

Then there's nothing much I can do about..
I'll try to ask some discord devs if they know why'd this fails, I'll keep you in touch whenever I get an update, I deeply apologise for the inconvenience.

**Comment by colduw** [comment]
@Rapougnac 
> Unfortunately, without more context i can't really do something, it may be related to https://github.com/Rapougnac/VixBluesky/issues/18

Hey, I think the issue here might be the oembed's author_name. It has a max allowed length of 256 (at least I believe so?), and if it surpasses that, the video (or, the entire thing for that matter) will straight up just not embed at all in my experience

**Comment by Lexedia** [comment]
> Hey, I think the issue here might be the oembed's author_name. It has a max allowed length of 256 (at least I believe so?), and if it surpasses that, the video (or, the entire thing for that matter) will straight up just not embed at all in my experience

Is that so? I always thought discord would substring the text to prevent this..
Might give it a shot tmrw, thanks for your suggestion, appreciate it <3

**Comment by colduw** [comment]
> Is that so? I always thought discord would substring the text to prevent this..

Yeah, the meta `og:description` does limit it, and does cut it off after a certain point, except the oembed's fields.. for some reason. Hope that's the issue here and not something else!

**Comment by Lexedia** [comment]
Well, apparently it was! I feel dumb lol, tysm for pointing that out!

**Comment by AmewaTakahashi** [comment]
So what was wrong? The embed kept failing and when I clicked on that link it shows me this
![image](https://github.com/user-attachments/assets/2f887301-3c56-4e87-963d-5d0c073703d4)
![image](https://github.com/user-attachments/assets/562f11fa-d0b8-4429-95fd-75504a7c7209)
