### ISSUE TITLE
Add video embed support

### ISSUE THREAD

**Issue by tuzonghua** [Lexedia/VixBluesky#6]
It's not officially official yet but Bluesky is adding video support. [Example post](https://bsky.app/profile/samuel.bsky.team/post/3l3oak6batq2a) (viewable on web or latest mobile app). `bskyx` should also embed the related video content.

**Comment by Valac-Design** [comment]
Bumping this, because my bot uses your url for embed routing, so we need to see some love for video.

**Comment by yellingatmeVT** [comment]
Bump because video is now a thing! Screenshots included to show (also I wish I knew your version for embeds sooner, much easier than typing out s/k/y all the time)
![Screenshot_20240911_200550_Bluesky](https://github.com/user-attachments/assets/86cbbabe-ac07-4cc9-986f-b46b8fbd6248)
![Screenshot_20240911_201028_Discord](https://github.com/user-attachments/assets/35d2b758-e81c-4f34-bbbb-bbdce93335a8)

**Comment by Lexedia** [comment]
Hi, I'm currently on vacation, I already started working on this, maybe I can release something by the end of the week, but no promises.

**Comment by Lexedia** [comment]
Yaaay, it works!

![image](https://github.com/user-attachments/assets/549f350c-dcb9-4820-a805-ddf64a7f7c90)

The deployment is local only currently, since for now, I need to transcode the video into something readable by discord, which involves a backend and some cpu resources :/

Anyways, I'll push the changes as-is tomorrow if you guys are okay to use a slow version (~1.5-2s to generate the video from a cold (not cached) skeet).

FWIW, I'll continue digging to see if the transcoding is avoidable, but I have slender hopes :^)

**Comment by Invertex** [comment]
> The deployment is local only currently, since for now, I need to transcode the video into something readable by discord, which involves a backend and some cpu resources :/

Just checking in case you just used the wrong term by accident, but if you're actually *transcoding*, you shouldn't need to do that. The streams appear to be H264-AVC encoded, so all that needs to be done for Discord to display them is to "remux" the streams into an mp4 container, which is a near instant operation compared to transcoding. But since you're saying only 1.5 to 2s I'm guessing you are remuxing, unless your server is pretty fast.

Thanks for getting on top of this so quick though! I was about to try doing it today myself lmao

**Comment by Lexedia** [comment]
>  But since you're saying only 1.5 to 2s I'm guessing you are remuxing, unless your server is pretty fast.

What coding at 2:00 does to a mf :fire: 

Yes, sorry for the mix of words, I managed to confuse myself while typing this.

**Comment by Lexedia** [comment]
It's implemented, changes are now live :D

**Comment by tuzonghua** [comment]
@Rapougnac Video works! But it's not including the text in the embed. :( I can open it as a separate issue if that'll keep things clean.

**Comment by Lexedia** [comment]
I know, I wanted to add a comment but completly forgor :sob:

I'd be happy if you open an issue, it'll not be my priority for now as I'm still in vacation and I need to get some fresh air.
I should be back next week, if it's really annoying, PRs are open, it shouldn't be too complicated to implement.

Sorry, hope everyone will understand

**Comment by Lexedia** [comment]
> I can open it as a separate issue if that'll keep things clean.

Since #8 exists, it's not needed anymore, thank you for your awareness though.
